boot.o: boot.S inc/multiboot.h inc/x86/desc.h inc/types.h
kernel.o: kernel.c inc/multiboot.h inc/types.h inc/x86/desc.h inc/lib.h \
 inc/i8259.h inc/debug.h
lib.o: lib.c inc/lib.h inc/types.h
desc.o: x86/desc.S inc/x86/desc.h inc/types.h
paging.o: x86/paging.S
keyboard.o: drivers/keyboard.c
rtc.o: drivers/rtc.c
i8259.o: pic/i8259.c inc/i8259.h inc/types.h inc/lib.h
err_handler.o: x86/err_handler.c
syscall_handler.o: x86/syscall_handler.c
